### ISSUE TITLE
WebNowPlaying stops updating after 5 minutes

### ISSUE THREAD

**Issue by Luminiferous348** [keifufu/WebNowPlaying-Spicetify#1]
After 5 Minutes, WebNowPlaying stops giving Information to Rainmeter, if Spotify is minimzed (either to the taskbar or the tray). If Spotify isn't minimized it seems to work fine. This issue affects all Measures. Bangs continue to work fine.

I run Spotify for Windows 1.2.10.760.g52970952 with Spicetify v2.18.0 and the as of writing current WebNowPlaying plugin.

On the Rainmeter side I run Rainmeter 4.5.17.3700 (64-bit) with the WebNowPlaying DLL Version 1.2.0.0.

This also seems to be the same issue as this one:
https://github.com/spicetify/spicetify-cli/issues/1390

**Comment by keifufu** [comment]
Hey, just making sure you're using the WebNowPlaying version from the spicetify marketplace and not the one you enable via the command line, right?

**Comment by Luminiferous348** [comment]
Yeah, I use the current WebNowPlaying-Redux from the marketplace. Sadly it doesn't give me a version number, so I can only say, that I use the latest version

**Comment by keifufu** [comment]
I'll look into it at some point this week.
There is a chance I'll abandon spicetify wnp as new WebNowPlaying versions (not yet released) can read and control Spotify without it.

**Comment by keifufu** [comment]
@Alpha272 I recommend using the new [Native APIs](https://github.com/keifufu/WebNowPlaying-Redux/blob/main/NativeAPIs.md) feature to get desktop players (like Spotify) to work.

The Rainmeter plugin should be updated very soon ^^
